#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for managing the camera virtual machines"""

# pylint: disable=invalid-name
# pylint: disable=broad-except

import glob
import os
import sys
import Pyro4
from rockit.camvirt import CommandStatus, Config

SCRIPT_NAME = os.path.basename(sys.argv[0])
sys.excepthook = Pyro4.util.excepthook


def run_command(command, args):
    """Runs a daemon command, handling error messages"""
    if 'CAMVIRTD_CONFIG_PATH' in os.environ:
        config = Config(os.environ['CAMVIRTD_CONFIG_PATH'])
    else:
        # Load the config file defined in the CAMVIRTD_CONFIG_PATH environment variable or from the
        # default system location (/etc/camvirtd/). Exit with an error if zero or multiple are found.
        files = glob.glob("/etc/camvirtd/*.json")
        if len(files) != 1:
            print('error: failed to guess the default config file. ' +
                  'Run as CAMVIRTD_CONFIG_PATH=/path/to/config.json camvirt <command>')
            return 1

        config = Config(files[0])

    try:
        ret = command(config, args)
    except Pyro4.errors.CommunicationError:
        ret = -101

    # Print message associated with error codes, except for -1 (error handled locally)
    if ret not in [-1, 0]:
        print(CommandStatus.message(ret))
    sys.exit(ret)


def initialize(config, *_):
    """Power-on managed virtual machines"""
    with config.daemon.connect(timeout=config.daemon.default_timeout + config.initialize_timeout) as camvirtd:
        return camvirtd.initialize()


def shutdown(config, *_):
    """Power-off managed virtual machines"""
    with config.daemon.connect(timeout=config.daemon.default_timeout + config.shutdown_timeout) as camvirtd:
        return camvirtd.shutdown()


def print_usage():
    """Prints the utility help"""
    print(f'usage: {SCRIPT_NAME} <command> [<args>]')
    print()
    print('general commands:')
    print('   init         power-on managed virtual machines')
    print('   kill         power-off managed virtual machines')
    print()
    return 0


if __name__ == '__main__':
    commands = {
        'init': initialize,
        'kill': shutdown
    }

    if len(sys.argv) >= 2 and sys.argv[1] in commands:
        sys.exit(run_command(commands[sys.argv[1]], sys.argv[2:]))

    sys.exit(print_usage())
